swagger: '2.0'
info:
  title: crypto-journal
  description: Crypto Journal API Spec
  version: 0.1.0
schemes:
  - https
produces:
  - application/json
x-google-backend:
  address: https://crypto-journal-api-bsia4lvk6q-nw.a.run.app
  jwt_audience: https://crypto-journal-gw-92zxtz6r.nw.gateway.dev
paths:
  /health:
    get:
      summary: Health check
      operationId: health
      security: []
      responses:
        '200':
          description: If service is running
          schema:
            type: string
  /addresses/{address}/positions:
    parameters:
      - in: 'path'
        name: 'address'
        type: 'string'
        required: true
    options:
      operationId: positionsOptions
      security: []
      responses:
        '200':
          description: Allow cors request
    get:
      summary: Get positions for given address
      operationId: getPositions
      security:
        - auth0_jwk: []
      responses:
        '200':
          description: Positions for address
        '204':
          description: Address has no positions
  /addresses/{address}/positions/{positionId}:
    parameters:
      - in: 'path'
        name: 'address'
        type: 'string'
        required: true
      - in: 'path'
        name: 'positionId'
        type: 'string'
        required: true
    options:
      operationId: positionOptions
      security: []
      responses:
        '200':
          description: Allow cors request
    get:
      summary: Get position by id
      operationId: getPosition
      security:
        - auth0_jwk: []
      responses:
        '200':
          description: Position for given id
  /positions/{positionId}/journal:
    parameters:
      - in: 'path'
        name: 'positionId'
        type: 'string'
        required: true
    options:
      operationId: journalOptions
      security: []
      responses:
        '200':
          description: Allow cors request
    put:
      summary: Upsert journal for positition
      operationId: upsertJournal
      security:
        - auth0_jwk: []
      parameters:
        - in: 'body'
          name: journalEntry
          required: true
          schema:
            type: object
            properties:
              notes:
                type: string
              tags:
                type: array
                items:
                  type: string
              mistakes:
                type: array
                items:
                  type: string
      responses:
        '200':
          description: Upsert success
  /portfolio/{address}/kpi:
    parameters:
      - in: 'path'
        name: 'address'
        type: 'string'
        required: true
    options:
      operationId: kpiOptions
      security: []
      responses:
        '200':
          description: Allow cors request
    get:
      summary: Get KPIs for given address
      operationId: getKpis
      responses:
        '200':
          description: KPIs for given address
  /portfolio/{address}/stats:
    parameters:
      - in: 'path'
        name: 'address'
        type: 'string'
        required: true
    options:
      operationId: statsOptions
      security: []
      responses:
        '200':
          description: Allow cors request
    get:
      summary: Get stats for given address
      operationId: getStats
      responses:
        '200':
          description: Stats for given address
  /wallets:
    options:
      operationId: walletsOptions
      security: []
      responses:
        '200':
          description: Allow cors request
    get:
      summary: Get addresses attached to the account
      operationId: getWallets
      security:
        - auth0_jwk: []
      responses:
        '200':
          description: Accounts wallets
        '204':
          description: Account has no wallets
        '500':
          description: Operation error
  /wallets/{address}:
    parameters:
      - in: 'path'
        name: 'address'
        type: 'string'
        required: true
    options:
      operationId: walletOptions
      security: []
      responses:
        '200':
          description: Allow cors request
    post:
      summary: Attach a new wallet address with the user's account
      operationId: createWallet
      security:
        - auth0_jwk: []
      responses:
        '201':
          description: Wallet has been attached to the user account
        '409':
          description: If the wallet address is already attached to the account
        '500':
          description: Operation failure
    delete:
      summary: Remove the given wallet address from the user's account
      operationId: deleteWallet
      security:
        - auth0_jwk: []
      responses:
        '200':
          description: Wallet removed
        '500':
          description: Operation failure
securityDefinitions:
  auth0_jwk:
    authorizationUrl: "https://dev-13qiy-8m.eu.auth0.com/authorize"
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://dev-13qiy-8m.eu.auth0.com/"
    x-google-jwks_uri: "https://dev-13qiy-8m.eu.auth0.com/.well-known/jwks.json"
    x-google-audiences: "https://crypto-journal-gw-92zxtz6r.nw.gateway.dev"